lang: en-US
title: Arindam Dev
logo: Image.jpg
email: arindam.dev.ad@gmail.com
description: Electrical Engineer
linkedin_username: arindam-dev-46385b91
show_downloads: false
google_analytics: 
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
