lang: en-US
title: Arindam Dev
logo: Image.jpg
email: arindam.dev.ad@gmail.com
description: Electrical Engineer
show_downloads: true
google_analytics: 
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
