title: Arindam dev
logo: Image.jpg
description: An ambitious and passionate electrical and electronic engineer with more than 6 years of experience in the power industry(including power transmission and distribution), who is highly motivated to embrace new challenges and opportunities in life.\Email: arindam.dev.ad@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
